%% Diagrama del Negocio NobleStep
flowchart TB
  classDef ext fill:#fff7ed,stroke:#9a3412,stroke-width:2px
  classDef proc fill:#ecfeff,stroke:#0e7490,stroke-width:2px
  classDef data fill:#f0fdf4,stroke:#166534,stroke-width:2px

  subgraph E1[Canales]
    CH1[Canal Ecommerce Angular]
    CH2[Canal Punto de Venta Interno]
  end

  subgraph P1[Gestion Comercial]
    P01[Autenticacion y control de acceso]
    P02[Gestion de usuarios internos]
    P03[Gestion de catalogo y variantes]
    P04[Gestion de clientes y proveedores]
    P05[Compras y reposicion de stock]
    P06[Ventas y descuento de stock]
    P07[Pedidos ecommerce y seguimiento]
    P08[Dashboard y reportes]
  end

  subgraph D1[Datos Core MySQL]
    D01[usuarios]
    D02[categorias productos variantes_producto]
    D03[clientes clientes_ecommerce proveedores]
    D04[ventas detalle_ventas]
    D05[compras detalle_compras]
    D06[pedidos detalle_pedidos]
  end

  EX1[API DNI RUC]
  EX2[Servicio Correo]

  CH1 --> P01
  CH1 --> P07
  CH1 --> P03

  CH2 --> P01
  CH2 --> P02
  CH2 --> P03
  CH2 --> P04
  CH2 --> P05
  CH2 --> P06
  CH2 --> P08

  P01 --> D01
  P02 --> D01
  P03 --> D02
  P04 --> D03
  P05 --> D05
  P05 --> D02
  P06 --> D04
  P06 --> D02
  P07 --> D06
  P07 --> D02
  P08 --> D04
  P08 --> D05
  P08 --> D02

  P04 --> EX1
  P07 --> EX2
  P01 --> EX2

  class EX1,EX2 ext
  class P01,P02,P03,P04,P05,P06,P07,P08 proc
  class D01,D02,D03,D04,D05,D06 data
