flowchart LR
  classDef actor fill:#fff,stroke:#111827,stroke-width:2px
  classDef app fill:#eef2ff,stroke:#3730a3,stroke-width:2px
  classDef data fill:#ecfdf5,stroke:#065f46,stroke-width:2px

  A1[Administrador Vendedor]
  N1[AutenticacionController]
  N2[AuthService]
  N3[TokenService]
  D1[Tabla usuarios]

  A1 -->|login refresh revoke| N1
  N1 --> N2
  N2 --> D1
  N2 --> N3
  N1 -->|jwt y refresh token| A1

  class A1 actor
  class N1,N2,N3 app
  class D1 data