flowchart LR
  classDef actor fill:#fff,stroke:#111827,stroke-width:2px
  classDef app fill:#eef2ff,stroke:#3730a3,stroke-width:2px
  classDef data fill:#ecfdf5,stroke:#065f46,stroke-width:2px
  classDef ext fill:#fff7ed,stroke:#9a3412,stroke-width:2px

  A1[Cliente Ecommerce]
  C1[AutenticacionEcommerceController]
  S1[TokenService]
  R1[Regla reset password con token hash expiracion]
  D1[clientes_ecommerce]
  X1[Servicio Correo]

  A1 -->|register login logout profile| C1
  A1 -->|forgot reset password| C1
  C1 --> S1
  C1 --> R1
  C1 --> D1
  C1 --> X1

  class A1 actor
  class C1,S1,R1 app
  class D1 data
  class X1 ext