flowchart LR
  classDef actor fill:#fff,stroke:#111827,stroke-width:2px
  classDef app fill:#eef2ff,stroke:#3730a3,stroke-width:2px
  classDef data fill:#ecfdf5,stroke:#065f46,stroke-width:2px
  classDef ext fill:#fff7ed,stroke:#9a3412,stroke-width:2px

  A1[Administrador]
  C1[AdminPedidosEcommerceController]
  C2[EventosController SSE base]
  D1[pedidos detalle_pedidos]
  X1[Servicio Correo]

  A1 -->|listar filtrar detalle exportar| C1
  A1 -->|stream SSE heartbeat| C2
  C1 -->|actualiza estado pedido y pago| D1
  C1 --> X1

  class A1 actor
  class C1,C2 app
  class D1 data
  class X1 ext